<?php

use Illuminate\Database\Seeder;

class TransaksisTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('transaksis')->delete();
        $data = [
            //user 7 nadiah
            [
                'id_user'=>7, 
                'id_toko'=>1, 
                'id_produk'=>1,
                'id_jenis'=>1,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>1,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'123as',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>4,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>7, 
                'id_toko'=>1, 
                'id_produk'=>2,
                'id_jenis'=>7,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>1,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>7, 
                'id_toko'=>1, 
                'id_produk'=>2,
                'id_jenis'=>7,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>1,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>7, 
                'id_toko'=>4, 
                'id_produk'=>8,
                'id_jenis'=>1,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>1,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>7, 
                'id_toko'=>1, 
                'id_produk'=>29,
                'id_jenis'=>6,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>1,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            //user 8 rafi
            [
                'id_user'=>8, 
                'id_toko'=>2, 
                'id_produk'=>60,
                'id_jenis'=>18,
                'id_kategori'=>3,
                'id_status'=>6,
                'id_alamat'=>7,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>8, 
                'id_toko'=>2, 
                'id_produk'=>48,
                'id_jenis'=>14,
                'id_kategori'=>2,
                'id_status'=>6,
                'id_alamat'=>7,
                'jumlah'=>1000,
                'subtotal'=>330000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>15000,
                'total_harga'=>48000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>8, 
                'id_toko'=>5, 
                'id_produk'=>33,
                'id_jenis'=>6,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>7,
                'jumlah'=>1000,
                'subtotal'=>48000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>15000,
                'total_harga'=>63000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            //user 10 deliana
            [
                'id_user'=>10, 
                'id_toko'=>6, 
                'id_produk'=>35,
                'id_jenis'=>7,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>9,
                'jumlah'=>1000,
                'subtotal'=>20000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'asf123',
                'biaya_ongkir'=>9000,
                'total_harga'=>29000,
                'rating'=>3,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
            [
                'id_user'=>10, 
                'id_toko'=>1, 
                'id_produk'=>1,
                'id_jenis'=>1,
                'id_kategori'=>1,
                'id_status'=>6,
                'id_alamat'=>9,
                'jumlah'=>2000,
                'subtotal'=>40000,
                'kirim_sekarang'=>true,
                'tgl_kirim'=>'2020-06-06',
                'kurir'=>'jne',
                'resi_kurir'=>'123as',
                'biaya_ongkir'=>18000,
                'total_harga'=>58000,
                'rating'=>4,
                'created_at'=>'2020-06-06 21:24:57',
                'updated_at'=>'2020-06-06 21:24:57'
            ],
        ];
        \DB::table('transaksis')->insert($data);
    }
}
